name: flutter_app
description: Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  connectivity_plus: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

assets:
    - assets/fonts/

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
  - family: LibreBaskerville
    fonts:
      - asset: assets/fonts/LibreBaskerville-Regular.ttf